#kat_kem.rsp: kat
#	./run

kat: Makefile nist/rng.c nist/rng.h randombytes.h benes.c bm.c controlbits.c decrypt_faulty.c encrypt_modified.c fft.c fft_tr.c gf.c int32_minmax_x86.c int32_sort.c operations.c pk_gen.c sk_gen.c vec128.c vec256.c  consts.S syndrome_asm.S transpose_64x128_sp_asm.S transpose_64x256_sp_asm.S transpose_64x64_asm.S update_asm.S vec128_mul_asm.S vec256_ama_asm.S vec256_maa_asm.S vec256_mul_asm.S vec_reduce_asm.S keccak/SimpleFIPS202.c keccak/KeccakSponge.c keccak/KeccakP-1600-opt64.c aes/aes.c aes/stream.c attack_sim.c 
	./build
